### ISSUE TITLE
No option to create icx wallet on the android ledger live app

### ISSUE THREAD

**Issue by FidelVe** [icon-project/ledger-app-icx#12]
After installing the android ledger live app I am able to install the ledger icon app without problems on a ledger nano X

![20200305_172403](https://user-images.githubusercontent.com/43641727/76059330-f1645f00-5f54-11ea-90d0-dbbf60213480.jpg)

After installing the app I should be able to create a icx wallet but searching for icx or icon shows no results that match the search criteria 

![20200305_172343](https://user-images.githubusercontent.com/43641727/76059441-39838180-5f55-11ea-831a-3b755cc6bfcb.jpg)

![20200305_172325](https://user-images.githubusercontent.com/43641727/76059458-46a07080-5f55-11ea-84d6-00e4c9434960.jpg)

**Comment by mksong76** [comment]
It supports just installing the ICON ledger application on your ledger device, not making transactions to ICON network. That functionality should be supported by ledger.com. Unfortunately, they have no plan to do that. You may use other available android wallet applications like https://play.google.com/store/apps/details?id=foundation.icon.iconex.

So, it's expected behavior to show nothing in "Crypto asset" menu.
