### ISSUE TITLE
BIP44 derivation path for coin_type ICX

### ISSUE THREAD

**Issue by FidelVe** [icon-project/ledger-app-icx#23]
Looking at [SLIP-0044 : Registered coin types for BIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) ICX was assigned `coin_type` slot *74*. I know this list is suppose to work as guide and not a hard stone standard so I checked in the [ICON Ledger JS API](https://github.com/icon-project/ledger-app-icx/tree/master/client-js) and the examples shows `coin_type` *4801368* 

```
import Transport from "@ledgerhq/hw-transport-u2f";
import Icx from "@ledgerhq/hw-app-icx";

const getIcxAddress = async () => {
  const transport = await TransportU2F.create();
  transport.setDebugMode(true);         // if you want to print log
  transport.setExchangeTimeout(60000);  // Set if you want to change U2F timeout. default: 30 sec

  const icx = new Icx(transport);
  // coin type: ICX(4801368), ICON testnet(1)
  const result = await icx.getAddress("44'/4801368'/0'", true, true);
  return result.address;
};
getIcxAddress().then(a => console.log(a));
```

The examples says "coin type: ICX(4801368), ICON testnet(1)" which is making me believe that this number was randomly used for testnet purposes.

I dont have a full grasp of how derivation paths work but I assume that If I select a different number for the `coin_type` the addresses that I will derive would be different, for example ithe addresses derived from path `"44'/74'/0'" would be different than the addresses derived from "44'/4801368'/0'"

If this is true than if I implement an ICON login (authentication) functionality in a webpage with support for ledger and use a derivation path that is not the same used in ICONex, I would be showing the users different public addresses to login than the ones shown in ICONex (as a note ICONex also use the derivation path 44'/4801368'/0' as seen on [line 83 in this file](https://github.com/icon-project/iconex_chrome_extension/blob/fea36be819dbe5a8a29a76e55cede9b38fee8632/src/app/components/WalletList/WalletList.js))

maybe im overthinking this or im a bit confused about derivation paths but it seems to me that is necessary to publish a standard in which it clearly show what derivation path all wallets and apps should use. To not break compatibility it seems that the derivation path to use should be `44'/4801368'/0'/0'/0'`, if this standard is to be created and published it should also describe what route should be used for the derivation of the consecutive addresses, for example `44'/4801368'/0'/0'/0'`, `44'/4801368'/0'/0'/1'`...`44'/4801368'/0'/0'/n'` or maybe `44'/4801368'/0'/0'/0'`, `44'/4801368'/1'/0'/0`... `44'/4801368'/n'/0'/0` (I think ledger uses this last one)

**Comment by bkbooth** [comment]
Hey @FidelVe 👋 Ben from ReliantNode here.

By the time we started working on MyIconWallet, ICONex was already well-established and using coin type _4801368_, rather than the BIP-44 coin type of _74_. Since we wanted MyIconWallet, and then Hana to support Ledger in the same way as users expected coming over from ICONex, we used the same coin type. So for Ledger, yes, definitely use coin type _4801368_ to be compatible with the rest of the ICON + Ledger ecosystem, I'm not super familiar with the Ledger apps themselves, but that coin type might be hardcoded in the ICON Ledger app itself?

I'm not sure the historic reason, but looking at some commit histories today it looks like `ledger-app-icx` was around before the BIP-44 spec was updated to add a coin type for ICON.

That said, since we introduced seed phrases / derived wallets when we built Hana, we do use the BIP-44 coin type of _74_ when deriving ICON wallets from seed phrases. We still use _4801368_ for Ledger addresses though (for backwards compatibility).

As for the full path, again we took what ICONex started and continued that: `44'/4801368'/0'/0'/{index}'`

So sequence is `44'/4801368'/0'/0'/0'`, `44'/4801368'/0'/0'/1'`, `44'/4801368'/0'/0'/2'`, ..., `44'/4801368'/0'/0'/n'`

**Comment by FidelVe** [comment]
Thank you so much for the reply, this really clears up a lot of my questions about how to implement this and maintain compatibility with the rest of the apps in the Ecosystem.

I think this thread can serve as a guide on how to go about this since we don't have a guideline published in the dev portal explicitly stating this. 

To summarize current `coin_type` for icx being use by all wallets and apps when it comes to ledger is `4801368` and the derivation path is `44'/4801368'/0'/0'/{index}'`

**Comment by bkbooth** [comment]
Yep, TLDR 👌

> To summarize current `coin_type` for icx being use by all wallets and apps when it comes to ledger is `4801368` and the derivation path is `44'/4801368'/0'/0'/{index}'`

**Comment by FidelVe** [comment]
Proposed a standard for this in the ICON IIP, it was [merged](https://github.com/icon-project/IIPs/pull/48) and can be consulted [here] (https://github.com/icon-project/IIPs/blob/master/IIPS/iip-48.md)
